spring:
  h2:
    console:
      enabled : true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  security:
    user:
      name: user
      password: 1111
      roles: USER
    oauth2:
      client:
        registration:
          google:
            clientId: 119220445198-nbilickndtnk43te919uefgtr09v0o4u.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
server:
  port: 9050

